### ISSUE TITLE
Fatal error    

### ISSUE THREAD

**Issue by vivek0198** [cardinity/client-bundle#2]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api.cardinity.com/v1/payments [status code] 400 [reason phrase] Bad Request' in /home/nordhish/public_html/payment/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89 Stack trace: #0 /home/nordhish/public_html/payment/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 /home/nordhish/public_html/payment/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 /home/nordhish/public_html/payment/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent)) #3 /home/nordhish/public_html/payment/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) in /home/nordhish/public_html/payment/src/Http/Guzzle/ExceptionMapper.php on line 89

**Comment by vaidasj** [comment]
This is business logic related exception. In your case you are providing invalid credit card number.
Please check exception getErrors() method for detailed list of errors occurred.

**Comment by vivek0198** [comment]
Hi  Team ,
I am already using   this method   to  catch the error  list , here the
 problem is  the  script  is turned into   fatal  error  while  making
 call  to call  using parameters in $method,
try {
    $payment = $client->call($method);
} catch (Exception\Declined $exception) {
 @type Cardinity\Method\Payment\Payment
    $payment = $exception->getResult();
    $status = $payment->getStatus(); // value will be 'declined'
    $errors = $exception->getErrors(); // list of errors occured
}

Regrads
Vivek Tyagi

**Comment by vaidasj** [comment]
You are catching only one specific Declined exception. Please refer to cardinity-sdk-php documentation regarding proper exception handling:
https://github.com/cardinity/cardinity-sdk-php/tree/master/docs#exceptions

In your case at least catch Cardinity\Exception\Request exception.

**Comment by vivek0198** [comment]
_Fatal error_: Uncaught exception 'GuzzleHttp\Exception\ClientException'
with message 'Client error response [url]
https://api.cardinity.com/v1/payments [status code] 400 [reason phrase] Bad
Request'

**Comment by vaidasj** [comment]
So just catch ClientException and see where the error comes from. Though we see that it's related to wrong credit card number.
